version: '3.8'

services:
  jerusalem-tunnel:
    build: .
    ports:
      - "1024-1100:1024-1100"
      - "1024:1024"
    environment:
      - SERVER_PORT=1024
      - PORT_RANGE=1024...1100
      - SECRET_KEY=2y6sUp8cBSfNDk7Jq5uLm0xHAIOb9ZGqE4hR1WVXtCwKjP3dYzvTn2QiFXe8rMb6
    entrypoint: [ "./jerusalem-tunnel" ]
    restart: always